import Head from "next/head";
import Image from "next/image";
import Crypto from "./components/Crypto";
import CryptoList from "./components/CryptoList";
import Layout from "./components/Layout";
import SearchBar from "./components/SearchBar";
import { useState } from "react";

export default function Home({ filteredCoins }) {
  const [search, setSearch] = useState("");
  

  const allCoins = filteredCoins.filter((crypto) =>
    crypto.name.toLowerCase().includes(search.toLowerCase())
  );

  const handleChange = (e) => {
    e.preventDefault();

    setSearch(e.target.value.toLowerCase());
  };


  return (
    <Layout>
      <Head>
        <title>CryptoCurrency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchBar onChange={handleChange} />

      <CryptoList filteredCoins={allCoins} />
    </Layout>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch(
    "https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&order=market_cap_desc&per_page=40&page=1&sparkline=false"
  );

  const filteredCoins = await res.json();

  return {
    props: {
      filteredCoins,
    },
  };
};
